notes_django/accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

notes_django/notes/urls.py
from django.urls import path
from .views import NoteListView, NoteDetailView, NoteUpdateView, NoteDeleteView, about, \
    NoteCommonListView, add_note

urlpatterns = [
    path('about/', about, name='about'),
    path('note/new/', add_note, name='note_new'),
    path('note/<int:pk>/', NoteDetailView.as_view(), name='note_detail'),
    path('note/<int:pk>/edit/', NoteUpdateView.as_view(), name='note_edit'),
    path('note/<int:pk>/delete/', NoteDeleteView.as_view(), name='note_delete'),
    path('', NoteCommonListView.as_view(), name='common'),
    path('home/', NoteListView.as_view(), name='home'),
]

notes_django/notes_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from notes_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('notes.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_django/accounts/models.py
from django.db import models

# Create your models here.

notes_django/notes/models.py
from django.db import models
from django.urls import reverse


class Note(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    body = models.TextField(blank=True, verbose_name='Текст')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    photo = models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')
    is_published = models.BooleanField(default=False, verbose_name='Видят все')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('note_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Заметки'
        verbose_name_plural = 'Заметки'
        ordering = ['-time_update', 'title']

notes_django/notes/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class AddNoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Note
        fields = ['title', 'body', 'photo', 'is_published', 'author']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')

        return title

notes_django/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

notes_django/notes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy


from .forms import *


def about(request):
    text = """На этом сайте могут оставлять заметки авторизованные пользователи.
    Записи можно делать приватными или публичными."""
    context = {
        'text': text,
    }
    return render(request, 'about.html', context=context)


class NoteListView(ListView):
    model = Note
    template_name = 'home.html'


class NoteCommonListView(ListView):
    model = Note
    template_name = 'common.html'


class NoteDetailView(DetailView):
    model = Note
    template_name = 'note_detail.html'
    fields = ['title', 'author', 'body', 'photo', 'time_create', 'time_update', 'is_published']


def add_note(request):
    if request.method == 'POST':
        form = AddNoteForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = AddNoteForm()
    return render(request, 'note_new.html', {'form': form, 'title': 'Добавление заметки'})


class NoteUpdateView(UpdateView):
    model = Note
    template_name = 'note_edit.html'
    fields = ['title', 'body', 'photo', 'is_published']

class NoteDeleteView(DeleteView):
    model = Note
    template_name = 'note_delete.html'
    success_url = reverse_lazy('home')

notes_django/templates/about.html
{% extends "base.html" %}

{% block content %}
<title>{{title}}</title>
<body>
<h5>{{text}}</h5>
</body>
{% endblock content %}

notes_django/templates/base.html
{% load static %}
{% load notes_tags %}
<html>
  <head>
	<link type="text/css" href="{% static 'css/base.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'images/logo.jpg' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
  <table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'common' %}"><div class="logo"></div></a></li>
			</ul>
			<div class="clear"></div>
		</div>
    <div>
      {% if user.is_authenticated %}
        <h3>Здравствуйте, {{ user.username }}.</h3>
        <p><a href="{% url 'logout' %}">Выйти из системы</a></p>
      {% else %}
        <h3>Вы не авторизованы.</h3>
        <a href="{% url 'login' %}">Авторизация</a> |
        <a href="{% url 'signup' %}">Регистрация</a>
      {% endif %}
        		</div>
<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
        {% show_notes request%}
	</ul>
</td>
<td valign="top" class="content">
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
</table>
</td></tr></table>
</td></tr>
  </body>
</html>

notes_django/templates/common.html
{% extends 'base.html' %}
{% load notes_tags %}
{% block content %}
<ul class="list-articles">
    {% for note in note_list %}
        {% if note.is_published == True %}
            {% if note.photo %}
			<p><img class="img-article-left thumb" src="{{note.photo.url}}"></p>
		{% endif %}
        <h2>{{note.title}}</h2>
		<li><div class="article-panel">
		<h5><a class="first">Дата создания: {{ note.time_create|date:'d-m-Y H:i' }}</a></h5>
		<h5><a class="last">Последнее изменение: {{ note.time_update|date:'d-m-Y H:i:s' }}</a></h5>
		</div>
		{% autoescape on %}
		<p>{{ note.body| linebreaks|truncatewords:50 }}</p>
		{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{note.get_absolute_url}}">Подробнее</a></p>
			</li>
        {% endif %}
  {% endfor %}

</ul>
{% endblock content %}

notes_django/templates/home.html
{% extends 'base.html' %}
{% load notes_tags %}
{% block content %}
{% if user.is_authenticated %}
<ul class="list-articles">
	{% for note in note_list %}
		{% if note.author.pk == request.user.pk %}
		{% if note.photo %}
			<p><img class="img-article-left thumb" src="{{note.photo.url}}"></p>
		{% endif %}
        <h2>{{note.title}}</h2>
		<li><div class="article-panel">
		<h5><a class="first">Дата создания: {{ note.time_create|date:'d-m-Y H:i' }}</a></h5>
		<h5><a class="last">Последнее изменение: {{ note.time_update|date:'d-m-Y H:i:s' }}</a></h5>
		</div>
		{% autoescape on %}
		<p>{{ note.body| linebreaks|truncatewords:50 }}</p>
		{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{note.get_absolute_url}}">Подробнее</a></p>
			</li>
	{% endif %}
	{% endfor %}
</ul>
      {% else %}
        <h3><p>Пожалуйста, авторизуйтесь или зарегистрируйтесь, чтобы оставлять заметки.</p></h3>
      {% endif %}
{% endblock %}

notes_django/templates/list_notes.html
{% for url in urls %}
	{% if current_url == url.url_name%}
		<title>{{url.title}}</title>
		<li class="selected"><h2>{{url.title}}</h2></li>
	{% else %}
		<li class="selected">
		<h3><a href="{% url url.url_name %}">{{url.title}}</a></h3>
		</li>
	{% endif %}
{% endfor %}

notes_django/templates/note_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Удаление записи</h1>
<form action="" method="post">{% csrf_token %}
  <p>Вы уверены, что хотите удалить "{{ note.title }}"?</p>
  <input type="submit" value="Подтверждение удаления">
</form>
{% endblock content %}

notes_django/templates/note_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="note-entry">
    <h2>{{ note.title }}</h2>
    <p>{{ note.body| linebreaks }}</p>
    {% if note.photo %}
        <h5>Изображение {{ note.photo }}</p></h5>
	    <p><img class="img-article-left thumb" src="{{note.photo.url}}"></p>
    {% endif %}
    <h5><p>Дата создания: {{ note.time_create|date:'d-m-Y H:i' }}</p></h5>
    <h5><p>Последнее изменение: {{ note.time_update|date:'d-m-Y H:i:s' }}</p></h5>
    {% if note.is_published == True %}
      <h5><p>Запись видят все</p></h5>
    {% else %}
      <h5><p>Запись видна только вам</p></h5>
    {% endif %}

  </div>
<p><a href="{% url 'note_edit' note.pk %}">Редактировать запись</a></p>
<p><a href="{% url 'note_delete' note.pk %}">Удалить запись</a></p>
{% endblock content %}

notes_django/templates/note_edit.html
{% extends "base.html" %}

{% block content %}
<h1>Редактирование записи</h1>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
<input type="submit" value="Изменение">
</form>

{% endblock content %}

notes_django/templates/note_new.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Новая заметка</h1>
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <input type="submit" value="Добавить">
    </form>
{% else %}
    <h3><p>Пожалуйста, авторизуйтесь или зарегистрируйтесь, чтобы оставлять заметки.</p></h3>
{% endif %}
{% endblock content %}